server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # "demo-service" 라우트 설정
        - id: demo-service-route
          # 목적지(URI)는 demo-service의 주소(docker NAME)
          uri: http://demo-service:8080
          # 조건(Predicates) 설정
          predicates:
            # "/demo/**" 패턴의 요청이 들어오면 이 라우트를 적용
            - Path=/demo/**
